### ISSUE TITLE
Easy Mod Installation

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#10]
In order to simplify mod installation I propose the following things
- Create BattleTechLoader.exe as a substitute for starting BattleTech.exe and that automatically patches any un-patched assemblies before starting BattleTech.exe automatically. Bascially a nice wrapper around BTML for users. Thats why Skyrim is doing.
- Bundle BTML and ModTek together on release of a new ModTek versions.

I also would merge ModTek and BTML repos at one point in time. I'm also aware that you want to have BTML and ModTek seperated, just have them as separate csprojects within the same .sln and definitely in the same repo . Unless BTML and ModTek gets bigger than the linux kernel, it makes no sense to have them in different git repos.

**Comment by Mpstark** [comment]
I like the behavior of "loading through" an .exe without patching existing files. This is the purview of BTML however, I'll open an issue over there with 

ModTek and BTML are separate projects with separate releases. I don't see any practical benefit from merging the two projects -- I understand that they have a lot of overlap and merging them wouldn't be a "wrong" thing to do.
