### ISSUE TITLE
Prevent encoding changeovers between contributers

### ISSUE THREAD

**Issue by Mpstark** [Mpstark/ModTek#16]
![image](https://user-images.githubusercontent.com/5605487/39772423-dd8dec38-52ba-11e8-90dd-bd7f517ed03b.png)

**Comment by CptMoore** [comment]
crln handling in git, how should that be managed? auto since maybe mac users could benefit from that?

**Comment by Tyler-IN** [comment]
First, I want to point out this isn't line endings related... next I'm gonna rable about line endings, and then I'm gonna defer to a short-term encoding solution in PR #19.

Git is currently set up to be eol=crlf for .sln and .csproj files, agnostic elsewhere.

The .editorconfig specifies LF exclusively. It might need to have exceptions for the sln/proj files.

Git *should* be agnostic, as users should configure their own line endings settings.

Mac and Linux are LF but support CRLF, VS on Windows is the CRLF holdout, but it can support LF-only endings by configuration.

On Windows, normally there's a transform that occurs changing CRLF to LF when committing, and another that converts LF to CRLF when checking out.

So this error is from encoding differences. Enforcing encoding can be automated by git hooks, but not with GitHub, they have to be manually linked per repo user. I could have the project ensure they're wired in before a build if desired, but I'd propose moving to somewhere like GitLab that supports hooks at the server.

Alternatively, this script can be integrated as part of a test suite, and have the CI run on PRs and such and fail when someone mucks with the encodings.

The script in #19 does not silently fix encodings, it just reports errors. I can change it to silently fix instead if preferred.  I also made a [PR #6](https://github.com/Mpstark/BattleTechModLoader/pull/6) over on BTML.

**Comment by Mpstark** [comment]
The [fix file encoding VS plugin](https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.FixFileEncoding) fixed have fixed this issue for me.

**Comment by Mpstark** [comment]
I've checked my commits, they're being cleaned up after properly I think. It's just diffing in VS gives the warning.
