### ISSUE TITLE
Move Mod Loading Out of Init

### ISSUE THREAD

**Issue by Mpstark** [Mpstark/ModTek#17]
Other BTML-based mods should load first, since they are not dependency tracked.

**Comment by CptMoore** [comment]
Is it possible to load all assemblies and afterwards start invoking the inits? This should count also for BTML as well as ModTek based mods.

That should allow mods outside and inside of ModTek to Harmonize each other before everything gets inited.

**Comment by Mpstark** [comment]
Explicit dependencies specified in `mod.json` cover the major use-case of Harmony patching other mod assemblies between mods setup with ModTek. With all BTML-only assemblies being loaded and ran before ModTek does it's load process, a ModTek-mod could then rely on BTML-loaded assemblies regardless of name.

**Comment by Tyler-IN** [comment]
Any opinion about parallel loading?

E.g. build dependency trees first, then a thread for initializing for each tree root?

**Comment by Mpstark** [comment]
Development branch has a working branch of this, which uses a new Harmony patch on DataManager's constructor to load mods.

@Tyler-IN Parallel loading would be great if we can figure out how to guarantee correctness and an actual speed increase.
