### ISSUE TITLE
Mods Adding To DB (and not breaking the game)

### ISSUE THREAD

**Issue by Mpstark** [Mpstark/ModTek#21]
`VersionManifestHotReload.InstantiateResourceAndUpdateMDDB` seems to be a good place to start -- it loads JSON from a path, deserializes it to a concrete object (if it's one of the MDDB types), and then updates the MDDB with the object.

If we can find an easy way of maintaining, i.e. removing mod entries in the DB for mods that have been deleted, then adding this feature seems to be fairly straightforward.

**Comment by thehawkyo** [comment]
Would it be possible just to have ModTek automatically back up the DB file and replace it with a provided, modded DB to load on instance?

**Comment by Mpstark** [comment]
In the development branch, I'm currently working with a duplicated DB that the game is redirected to. I'm working on tracking mod DB entries to keep that DB in line with the currently installed and enabled mods.

**Comment by Mpstark** [comment]
This is now released in ModTek 0.2.0
