### ISSUE TITLE
HBS JSON has errors preventing mod JSON merging

### ISSUE THREAD

**Issue by TimeDiver0** [Mpstark/ModTek#31]
Said file(s) contain an array missing a comma; the game engine cheerfully ignores these, but ModTek and the BMIT (Metadatabase Import Tool) do not (and rightfully so?).

In particular, SimGameConstants.json is missing a comma at line 548 in the "Progression" array, which threw off my re-arranged MechWarrior skill tree setup.

Editing the original file in 'data\simGameConstants' got rid of the error message and let my changes go through.

**Comment by CptMoore** [comment]
Your regex idea is ok.

`grep -REzl ",\s*\]" --include "*.json" .`
```
./data/audioevents/audioeventdef_uiinteractions.json
./data/behaviorVariables/global_def.json
./data/behaviorVariables/global_sensorlock.json
./data/behaviorVariables/personality_aggressive.json
./data/behaviorVariables/personality_disciplined.json
./data/behaviorVariables/personality_qapersonality.json
./data/behaviorVariables/role_flanker.json
./data/behaviorVariables/role_meleeonly.json
./data/behaviorVariables/role_scout.json
./data/behaviorVariables/role_sniper.json
./data/behaviorVariables/role_spotter.json
./data/behaviorVariables/role_vehicle.json
./data/behaviorVariables/unused.json
./data/debug/MultiplayerCombat_Verbose.json
./data/hardpoints/hardpointdatadef_stalker.json
./data/lance/lancedef_mixed_d1_dynamic_lightCavalry.json
./data/pilot/pilot_kbeta_ozone.json
./data/shops/shopdef_Upgrades_0.json
./data/simGameConstants/SimGameConstants.json
./data/turretChassis/turretchassisdef_testturret_360.json
./data/vehicle/vehicledef_AMMOTRANSPORT.json
./data/vehicle/vehicledef_MOBILEHQ.json
./data/vehicle/vehicledef_MOBILEHQ_ARMORED.json
./data/vehicleChassis/vehiclechassisdef_BULLDOG.json
./data/vehicleChassis/vehiclechassisdef_SLDFDroneMedium.json
./data/vehicleChassis/vehiclechassisdef_TARGETVEHICLE2.json
```

looks alright going through those, I would use the regex `,\s*\]` as a preprocessor step.

**Comment by Mpstark** [comment]
The serializer happily takes extra commas. Its the missing ones cause the most issues.

**Comment by CptMoore** [comment]
oh you mean missing commas?

**Comment by CptMoore** [comment]
`"\s*\n\s*"` finds all offending places, just replace that with `",\n"`note the `"` quotes are part of the regex. Json actually doesn't support actual newline characters in values, so we can happily parse for them

**Comment by Feylan** [comment]
Just some additional data points from my own testing with various mods, I've identified the following files that are missing commas in their original, unmodified state:

.\data\milestones\milestone_304_notify_mechs.json
.\data\milestones\milestone_563_sim_argo.json
.\data\milestones\milestone_652_notify_systemTravel_3.json
.\data\shops\shopdef_Mech_2.json
.\data\shops\shopdef_Mech_battlefield.json
.\data\shops\shopdef_Mech_Davion.json
.\data\shops\shopdef_Mech_Liao.json
.\data\shops\shopdef_Mech_Marik.json

No guarantee this is comprehensive. Personally I'd recommend either fixing the base JSONs (at runtime for each first run of a new game version) or if possible, shifting over to fastjson (https://github.com/alibaba/fastjson) if it's handling these errors without apparent issue.

[ModTek.log](https://github.com/Mpstark/ModTek/files/1994435/ModTek.log)

**Comment by CptMoore** [comment]
@Feylan my regex "\s*\n\s*" seems to find your files and many more except for 2 you mentioned:
* .\data\milestones\milestone_563_sim_argo.json
* .\data\shops\shopdef_Mech_Marik.json

can you check where commas are missing there? couldn't see them myself.

```
CombatGameConstants.json
TooltipSimGameCharacterSUMIRE.json
LoreADV.json
LoreAuriganCoalition.json
LoreBloodChit.json
LoreComStarPrecentor.json
LoreGaussRifle.json
LoreGreatHouses.json
LoreHighLordTamatiArano.json
LoreHolovidMercenaries.json
LoreMercenaryReviewBoard.json
LoreOutpostCastle.json
LorePiratePoint.json
LorePulseLaser.json
lancedef_mech_d1_dynamic_solo.json
lancedef_mech_d2_dynamic_solo.json
lancedef_mech_d4_dynamic_solo.json
lancedef_mech_d5_dynamic_solo.json
lancedef_mech_d6_dynamic_solo.json
lancedef_mech_d7_dynamic_solo.json
lancedef_mech_d8_dynamic_solo.json
lancedef_mech_d9_dynamic_solo.json
mechdef_highlander_HGN-732b.json
milestone_304_notify_mechs.json
milestone_652_notify_systemTravel_3.json
pilot_d10_BL_sentinel.json
pilot_d6_BL_sentinel.json
pilot_d7_BL_sentinel.json
pilot_d8_BL_sentinel.json
pilot_d9_BL_sentinel.json
pilot_story_victoriaMid.json
shopdef_Mech_2.json
shopdef_Mech_battlefield.json
shopdef_Mech_Davion.json
shopdef_Mech_Liao.json
SimGameConstants.json
WeaponTemplate.json
```

**Comment by Mpstark** [comment]
Yeah, we'll play with it and see if we can find something that works. There are also non-jarray, non-jobject, non-string values to look for like:

```json
{
    "Hello" = 8
    "Goodbye" = 6
}
```

**Comment by CptMoore** [comment]
```
        internal static string FixMissingCommas(string json)
        {
            var pattern = @"(\]|\}|"")\s*\n\s*(\[|\{|"")";
            var replacement = "$1,$2";
            var rgx = new Regex(pattern);
            return rgx.Replace(json, replacement);
        }
```
and your retry idea worked fine for the current game files I'm modifying

**Comment by Feylan** [comment]
@CptMoore milestone_563_sim_argo.json contained a double comma after the "Added Tags" portion of Results. I know that double commas were noted as not causing issues, but it did show up in the log, so perhaps also checking for them may be in order.

If file repair only occurs on a failure to load I'm sure performance won't suffer to badly, but I do like the idea of hash based cashing; it allows for additional operation on vanilla game files if necessary after any modifications from an official patch.

**Comment by CptMoore** [comment]
thanks, I think its time to write hbs about their json quality ...

**Comment by Mpstark** [comment]
I'm closing this issue, we've done all that we can.
