### ISSUE TITLE
OSX: ModTek search path for Mods folder broken

### ISSUE THREAD

**Issue by ffaristocrat** [Mpstark/ModTek#33]
Backslash isn't used for directory navigation on OSX. As a result, ModTek creates & uses a folder literally named `..\..\..\Mods`.

It needs to navigate the directory structure in an OS agnostic way.

This is the same issue that BTML has.

**Comment by Mpstark** [comment]
I'll prob merge tomorrow, I see no issues with this right now, but I obviously will want to try it out, make sure it doesn't break in my setup.

**Comment by CptMoore** [comment]
@ffaristocrat are you using steam to test on OSX? Can you tell me the directory structure of where battletech is located in relation to steam?

**Comment by ffaristocrat** [comment]
Here's the full path down to the Mods folder.

`/Users/ffaristocrat/Library/Application Support/Steam/SteamApps/common/BATTLETECH/BattleTech.app/Contents/Resources/Mods`
