### ISSUE TITLE
Cache merged JSONs to disk

### ISSUE THREAD

**Issue by Mpstark** [Mpstark/ModTek#39]

**Comment by CptMoore** [comment]
yes, that will help with debugging. to that note, I would like an extra file showing the current load order, like loadorder.txt or loardorder.tmp (indiracting thats its generated)

**Comment by Mpstark** [comment]
This behavior is now in the development branch, along with the loadorder thing. Loadorder is not currently loaded from the load_order.json yet, but will be.

**Comment by CptMoore** [comment]
I saw you removed JSONSerializationUtility_StripHBSCommentsFromJSON_Patch

so your intention is as follows?
- create a directory full of merged jsons
- patch the manifest loading and build a new manifest with paths pointing to the merged jsons

**Comment by Mpstark** [comment]
Yes.

**Comment by Mpstark** [comment]
This is contained in 0.1.5-alpha, closing the issue.
