### ISSUE TITLE
Advanced JSON merging

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#40]
found the solution we need, JSONPath

```
var o1 = JObject.Parse(json);
var o2 = JObject.Parse(json2);

var path = "client.spouse";
o1.SelectToken(path).Replace(o2.SelectToken(path));

var path2 = "client.email";
o1.SelectToken(path2).Replace(o2.SelectToken(path2));
```

paths are for inside jsons, so we need to define something in the direction of the following:
```
"modifications": {
  "fileToBeModified": "filePathTo.json",
  "fileForNewData": "filePath2To.json",
  "replacements": [
    {
      "jsonPathToOldValue": "jsonPathSyntax",
      "jsonPathToNewValue":  "jsonPathSyntax"
    }
  ]
}
```

sometimes you want to just directly merge in values, so why even retrieve from another file?
```
"modifications": {
  "fileToBeModified": "filePathTo.json",
  "replacements": [
    {
      "jsonPath: "jsonPathSyntax",
      "value":  [ "kraken "]
    }
  ]
}
```

since this can still be reduced, and we actually just want to modify existing files with this, lets create a mirror json with a different ending.

> SimGameConstants.replacements.json
```
[
  {
    "jsonPath: "$.Travel.HabitablePlanetTags[2]",
    "action": "replace,
    "value":  "planet_climate_snow"
  },
  {
    "jsonPath: "$.Travel.HabitablePlanetTags[1]",
    "action":  "remove"
  },
  {
    "jsonPath: "$.Travel.HabitablePlanetTags",
    "action": "add",
    "value":  "planet_climate_space"
  },
  {
    "jsonPath: "$.Travel.HabitablePlanetTags",
    "action": "replace",
    "externalJsonFile": "myplanettags.json",
    "externalJsonPath": "$.HabitablePlanetTags"
  },
  {
    "jsonPath: "$.Travel",
    "action": "add",
    "value":  { "somekey": "if Travel is a dict either overwrite or add somekey," }
  },
]
```

**Comment by Mpstark** [comment]
I've seen it, even used it to find the ID's from JSON. I'll look into what it would take to add this.

**Comment by CptMoore** [comment]
I made some structure and naming proposals for this. See last example.

**Comment by CptMoore** [comment]
@Mpstark I thought about the last proposal I made and can't find anything better. there is [jq](https://stedolan.github.io/jq/) which is a cmdline utility that wants to be sed for json, but that looks more complicated than what is proposed here.

I would like to start implementing this as I need this for some of my mods. any objections or or do you have any cross-checking you want to do first?
I'd be just implementing the whole language / content part first and make a PR to look at it.

**Comment by Mpstark** [comment]
I don't particularly like the idea of having files in the mirror path that don't act like the others. I would much prefer a new "Type" in the manifest for this thing.

**Comment by CptMoore** [comment]
I just added everything except the loading, so feel free to integrate it into ModTek as you see fit or give me some guidelines on how exactly it should be integrated

**Comment by CptMoore** [comment]
was added
