### ISSUE TITLE
Further documentation issues

### ISSUE THREAD

**Issue by mlangsdorf** [Mpstark/ModTek#42]
Suggestion:
While mentioning ModTek's super helpful logs, you might want to also mention HBS's log in Battletech_data/output_log.txt . It is very useful for figuring how you screwed up the json this time.

Clarification needed:
In the Manifest, what are valid entries for the Type key? MechDef, ChassisDef, WeaponDef, Texture2D, and Sprite are demonstrated, but there's a lot of other things that might need to be declared in the Manifest: hardpoints, heatsinks, movement, pilot, portraits, shops, starsystems, upgrades, vehicles. Eventually there will be others like assetbundles. It isn't obvious what should be declared as a Type: Xdef and what should be declared as Type: Directory.

My current question is how to add new pilots, but its a general issue.

**Comment by Mpstark** [comment]
The manifest types are all the BattleTech resource types, there are... many. All types should be declared explicitly for manifest entries. "MechDef" for all mechs, etc. I don't really understand what you mean about "Type: Directory".

Pilots are added by adding their PilotDef, but they won't appear in the campaign unless you add the pilot into the DB.

**Comment by mlangsdorf** [comment]
By "Type: Directory", I meant stuff like:
 { "Type": "Texture2D",  "Path": "emblems\\", "AddToAddendum": "PlayerEmblems" }
which looks like a directory name and not a *Def. But now I see that it's just a coincidence.

How hard would it be to add support in ModTek for adding stuff to the database?

**Comment by Mpstark** [comment]
There's an experimental mode called "break.my.game" that tries to add to the DB. You can enable it by putting a file (generally a blank text one) with the name "break.my.game" in the mods directory. It adds substantially to the load times and just overall it's not very good.

I'm hoping to polish it up a lot and have it be a base feature.
