### ISSUE TITLE
files in structure deeper than 1 folder from data refuse to load or be inserted correctly.

### ISSUE THREAD

**Issue by Gungy** [Mpstark/ModTek#43]
I have tried in vain to add some missions using this tool and they are not recognised by the game.

seems anything that needs to be loaded 2 folders deep fails

data/contracts/assassinate/mission.json

seems to only like 

data/mechs/mech.json etc

**Comment by Mpstark** [comment]
The search should be recursively going through all subfolders. Mind zipping up your mod and uploading it to this issue?

**Comment by Gungy** [comment]
not really I deleted it all, seems copying a .csv and .db and keeping my mod in the streamingassets/mods is far easier for me. 

my main issue is if I put the missions in the streaming assets structure in the mod, modtek didnt load the files. 
StreamingAssets\data\contracts\assassinate\.json
it instead tried to over write/merge files that didnt exist.
and I couldn't add them via the mod.json because i cant figure out how to add that assassinate folder. and modtek refused to load the .json files in it. it would only look in the contracts folder it would seem.

If removed the assassinate folder and dropped the missions into the mycontracts folder the game refused to load the main menu. seems they have to be in the contract type sub folder so the assassinate is required.

**Comment by TimeDiver0** [comment]
Can't say that I've had this issue myself; I also have the <ModName>/StreamingAssets folder setup, with 'data' being the overwrites, and 'mods' being the new/added files.

Maybe that's the issue; by dumping them in '<ModName>/StreamingAssets/data', ModTek assumes by default that your mod is trying to overwrite files that aren't there.

In my case, I have the following setup for my personalized mod's mod.json:

```
{
	"Name": "Custom",
	"Version": "1.0.0",
	"Enabled": true,
	"DependsOn": ["StatsFixMod"], /* this is so it loads last, overriding mods loaded before it */
	"ConflictsWith": [],
	"Manifest": [
	{
		"Type": "AbilityDef",
		"Path": "StreamingAssets/mods/abilities"
	},
	{
		"Type": "AmmunitionBoxDef",
		"Path": "StreamingAssets/mods/ammunitionBox"
	},
	{
		"Type": "ChassisDef",
		"Path": "StreamingAssets/mods/chassis"
	},
	{
		"Type": "HeatSinkDef",
		"Path": "StreamingAssets/mods/heatsinks"
	},
	{
		"Type": "MechDef",
		"Path": "StreamingAssets/mods/mech"
	},
	{
		"Type": "JumpJetDef",
		"Path": "StreamingAssets/mods/jumpjets"
	},
	{
		"Type": "ShopDef",
		"Path": "StreamingAssets/mods/shops"
	},
	{
		"Type": "UpgradeDef",
		"Path": "StreamingAssets/mods/upgrades"
	},
	{
		"Type": "WeaponDef",
		"Path": "StreamingAssets/mods/weapon"
	}
	]
}
```

Aside from _horrifically_ increasing my initial load times by almost/over two minutes (I've got a **lot** of added files in those folders), I haven't experienced your issue.

**Comment by Gungy** [comment]
{
		"Type": "WeaponDef",
		"Path": "StreamingAssets/mods/contracts/assassinate"
	}

Fails for me

**Comment by TimeDiver0** [comment]
Pretty much, although you can leave out "/assassinate".

Just having the "StreamingAssets/mods/contracts" portion will result in ModTek including all sub-folders and files within of the "Type" ContractOverride.

Take a look at the ModTek.log file afterwards, for confirmation that it has _actually_ done so, though.

**Comment by Mpstark** [comment]
It's a bad idea to include new files in the StreamingAssets path in your mod-folder -- ModTek expects that everything in this folder merges-with/replaces existing entries from the StreamingAssets folder. 

You should have your new files in non-StreamingAssets paths and specify them in the manifest.

**Comment by Gungy** [comment]
{ "Type": "ContractOverride", "Path": "contracts" },

Game refuses to load, modtek log is fine, but the game gives FPS counter instead of menu.

**Comment by Mpstark** [comment]
Check output_log.txt, or upload it

**Comment by Mpstark** [comment]
It's in the BattleTech_Data directory

**Comment by Mpstark** [comment]
Closing this issue since OP didn't respond.
