### ISSUE TITLE
ModTek.dll

### ISSUE THREAD

**Issue by odtoy** [Mpstark/ModTek#49]
ModTek.dll is not showing up i have read through the set up  and deleted and re-extracted the 7z file but no luck i am completely new to this type of thing so i most likely screwed up at some point

**Comment by robertovdmeer** [comment]
7zip file? you need to download the .dll from https://github.com/Mpstark/ModTek/releases
and play that in mods/ folder
What exactly do you mean "Not showing up"?
You do have https://github.com/Mpstark/BattleTechModLoader installed and set up?

**Comment by Mpstark** [comment]
You have to download a release from [this page](https://github.com/Mpstark/ModTek/releases), otherwise you're downloading the source code.

**Comment by robertovdmeer** [comment]
I did, and the source code for looking into it

**Comment by Mpstark** [comment]
I was replying to the other guy lol

**Comment by robertovdmeer** [comment]
Whoops sry was on the bicycle ;p
