### ISSUE TITLE
Modtek (and game startup) hangs if no mods with mod.json in mod dir

### ISSUE THREAD

**Issue by robertovdmeer** [Mpstark/ModTek#51]
When starting a game with no mods that have a mod.json file, the game will hang at splash screen.

It turns out that Modtek Field modLoadOrder never gets instantiated but is used in a foreach loop.
`TryAddToVersionManifest(VersionManifest manifest)` calls
```
 if (!hasLoadedMods)
 LoadMods();
```
and continues on to `foreach (var modName in modLoadOrder)` where code execution stops.

Possible Solutions:
* Check hasLoadedMods again after LoadMods
* Have LoadMods return a boolean (this might also be useful for the Prefix and PostFix patches, as they both run it)
* Instantiate modLoadOrder

I'd submit a pull request but don't know your programming standards.

**Comment by Mpstark** [comment]
I've added a fix to the next release for this issue.
