### ISSUE TITLE
v0.2.0: How to exclude 'mech variants from being imported into MetadataDatabase.db?

### ISSUE THREAD

**Issue by TimeDiver0** [Mpstark/ModTek#59]
Other than using the 'BLACKLISTED' tag in the .mechdef file(s) in question, that is; because several of mine are downright illegal, but I want to be able to use/modify them in Skirmish Mode.

Alternatively, getting SQLiteDatabaseBrowser and removing the entries _each and every time_ the game is loaded (tiresome), **or** setting the created .db file to read-only after the initial creation/editing.

So... which approach is most appropriate/convenient for the conscientious end-user/modder?

**Comment by Mpstark** [comment]
I'll add a mod.json field for this usecase soon

**Comment by TimeDiver0** [comment]
Slight follow-up on this:

Setting the created MetadataDatabase.db file to read-only, while preventing un-wanted overwrites after a one-time clean-out of created 'mech variants/weapons, causes the tactical game layer to stutter like nothing else.

_However!_ Removing the read-only flag **after** the initial game load sequence, both prevents the un-wanted .db file being edited, AND removes the stutter.

Ran several test cases, including disabling every non-essential mod (i.e., those that wouldn't result in an infinite-duration loading screen), and _**that**_ one change made the difference.

**Comment by Mpstark** [comment]
I've added this to the master branch, it'll be in the next release. If you'd like this feature now, I've attached a ModTek.dll (in a zip) with it below. Just add `"AddToDB": false` to your manifest entries that you'd like to not be added to the db.

```json
"Manifest": [
    { "Type": "MechDef", "Path": "MechDefs", "AddToDB": false }
]
```

[ModTek.zip](https://github.com/Mpstark/ModTek/files/2064273/ModTek.zip)
