### ISSUE TITLE
Cache/[..]/StreamingAssets empty

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#61]
The merge_cache.json and type_cache.json were filled with info but the actual streamingassets* merged files were missing. It then complained when trying to add stuff to the mddb as the jsons were missing.

That happened when removing full (non-merged) json files from a mod that were added through the manifest.

Removing merge_cache.json and type_cache.json allowed the merged files to properly appear on next startup and everything works.

* not sure anymore if the BattleTech_Data was empty or the StreamingAssets subfolder, I'm only sure that all merged jsons were missing.

**Comment by Mpstark** [comment]
See if you can build up some replication steps for this, if you feel if it's still an issue.

**Comment by CptMoore** [comment]
It didnt happen again for me all this time, so Ill close this
