### ISSUE TITLE
Avira Flags BattleTechModLoaderInjector.exe as HEUR/APC (Cloud)

### ISSUE THREAD

**Issue by drlamana** [Mpstark/ModTek#63]
When you run the injector, Avira will flag and remove the file citing HEUR/APC (Cloud) pattern match.

**Comment by 0x1mason** [comment]
Can you simply ignore the file? https://blog.avira.com/exceptions-avira-antivirus-3-steps/

**Comment by Mpstark** [comment]
This isn't pertinent to ModTek. BTML has several issues open about being falsely flagged as malware.
