### ISSUE TITLE
Request: Allow single to multiple json merging

### ISSUE THREAD

**Issue by Nodachi216** [Mpstark/ModTek#66]
Here's what I want to be able to do, take a single json (defined in the mod.json file) and apply its changes across all jsons of a particular type or location.

Practical usage example: Make a single json containing mech hardpoint data and apply it to all chassis files.

**Comment by CptMoore** [comment]
I think that would work great with the json manipulation code currently in works (#40).

The json manipulations says what to change how inside a file (you can surgically change hardpoint data), and then you only need a wildcard to apply those to several files.

**Comment by Mpstark** [comment]
This is definitely what @CptMoore is working on with the "Advanced Merge" feature. I'm not sure when it'll be included, but I definitely want "ModuleManager" type functionality available in ModTek.

**Comment by Mpstark** [comment]
Closing as a duplicate of #40
