### ISSUE TITLE
Allow mods to overwrite settings from another mod

### ISSUE THREAD

**Issue by CptMoore** [Mpstark/ModTek#7]
if a mod provides settings and a follow up mod wants those settings to be overwritten, what is the best way of doing this?

mod A
- dmgForLRMAfter200m=4

mod B depends on mod A
- wants dmgFOrLRMsAfter200m=20
- colorEffectForOutOfRangeLRMs=red

allow to merge jsons for settings too? but those would need to be merged before mod A is initialized

**Comment by Mpstark** [comment]
I don't particularly like the idea of propagating settings forward -- it would be user-hostile and complicated to implement.

**Comment by CptMoore** [comment]
in this case, mods should not propagate anything they want overriden though settings. an mod/dll/assembly that allows to be configure should have a public configuration class that can be used by other mods for configuration
