### ISSUE TITLE
Modtek version not showing up

### ISSUE THREAD

**Issue by madrigal9** [Mpstark/ModTek#70]
I copied the two dlls and the exe from the BTML into the managed folder and ran the exe as administrator and the injection succeeded.  I copied the modtek.dll into a Mods folder I created.
When I run Battletech I do not see the version number for Modtek.

I have the GOG.com version 1.0.4-280D.

I was trying to setup Roguetech.   Any ideas?
The BTML version was 0.2.2 and the modtek was 0.2.2.29499

**Comment by Mpstark** [comment]
Screenshots of your mods folder and the managed folder?

**Comment by madrigal9** [comment]
Will do when I get home from work.


Thanks,
Dave



-----Original Message-----

**Comment by madrigal9** [comment]
Found my issue.  I accidentally created the mods folder inside the BattleTech_Data folder instead of the root of the Battletech folder.  My failure to follow your instructions.  Thanks for getting back to me.  Next step to try out RogueTech.  :)
